Sprint 5/step 1
101st/react-burger pull request #5
Opened 2023-03-20 12:26 UTC by 101st

Местами остались any, чуть позже буду править сейчас совсем нет времени.
Есть огрехи вёрстки и прыжков, так как не стал делать лоадеры.

2023-03-20 13:04 UTC, andryxxa93 requested changes
Здравствуйте! Хорошая работа 👍 
Что понравилось: 
- Хорошо типизировали хранилище
- Сокеты открываются и закрываются согласно тех заданию
- Правильно типизировали хуки `useDispatch` и `useSelector`

**Необходимо исправить**
- Дублируемые ингредиенты в заказе надо так же подсчитывать как и с булками.

![Снимок экрана 2023-03-20 в 15 51 17](https://user-images.githubusercontent.com/60173362/226344586-10662446-59b3-48ed-9cb4-9eee5e0e43f6.png)
![Снимок экрана 2023-03-20 в 15 50 47](https://user-images.githubusercontent.com/60173362/226344589-f8bc79c7-d7c8-4c38-b0c9-bb7a746a2ac5.png)

- При открытии конкретного заказа из "Истории заказов" ничего не отображается.

https://user-images.githubusercontent.com/60173362/226345042-014066fe-4f19-476d-bfc6-fb8fde74557c.mov


**Можно лучше**
- При открытии конкретного заказа из `Ленты заказов` - очень много повторяются запросов сокета, хотя при открытии просто "Ленты заказов" такого нет.
![Снимок экрана 2023-03-20 в 15 49 00](https://user-images.githubusercontent.com/60173362/226343412-a8e5d77a-42c9-40bb-b977-38da0cd31b15.png)

- Нужно организовать раздельное хранение данных в хранилище Redux, получаемых от сокета для авторизованного и неавторизованного пользователей. Иначе сейчас при заходе на страницу "История заказов" сначала на пару секунд видно данные из "Ленты заказов".

- Нужно рассматривать разный набор экшенов при работе с сокетом для авторизованного и неавторизованного пользователя, и задавать свой набор экшенов как аргумент при вызовах миддлвара wsMiddleware в configureStore.


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-20 13:04 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.tsx
> +  const { ingredients } = useAppSelector(store => store.ingredients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-20 13:04 UTC, andryxxa93 commented on src/utils/cookies.ts
> +export const setCookie = (name: string, value: string, options: { [name: string]: any } = {}) => { //TODO пока не понял как от этого избавиться
**Можно лучше**
Тут так же можно так вот поступить
```
props: {
  path?: string
  expires?: Date | string | number
  [propName: string]: any
}
```

2023-03-20 13:04 UTC, andryxxa93 commented on src/utils/ws.ts
> +        socket.onmessage = ({ data }) => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-03-20 13:04 UTC, andryxxa93 commented on src/components/app/app.tsx
> +  const background = (location.state as any)?.background; //TODO пока не понял как от этого избавиться
**Можно лучше**
Можно избавиться вот так -
```


interface LocationState {
  from: {
    pathname: string;
  };
}

  const location = useLocation<LocationState>();
```

2023-03-22 20:16 UTC, andryxxa93 commented
- При открытии конкретного заказа из "Истории заказов" - пустая модалка.

<img width="1431" alt="Снимок экрана 2023-03-22 в 23 15 16" src="https://user-images.githubusercontent.com/60173362/227027343-e8326be7-1c02-4807-98f8-670e6e7f6831.png">

2023-03-23 04:38 UTC, 101st commented
https://user-images.githubusercontent.com/1930875/227104531-eb1e32d3-f3bb-4df3-854f-3b0508a2a83b.mov

Ещё вот совсем недавно такое появилось. D&D странно себя ведёт как-то. Удалось поймать этот баг, он не всегда есть. В момент перетаскивания, элемент летит откуда-то сверху.

2023-03-23 08:42 UTC, andryxxa93 commented
> Ещё вот совсем недавно такое появилось. D&D странно себя ведёт как-то. Удалось поймать этот баг, он не всегда есть. В момент перетаскивания, элемент летит откуда-то сверху.

Да, правда, есть такое и не только у вас. Думаю, что это дело не в коде а в библиотеке или браузере.

2023-03-23 08:42 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-23 12:09 UTC, merged